spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/app
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop # 매 번 테이블 application을 종료할 때 drop, 시작할 때 create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace # 로그 레벨 설정 추가

app:
  host: http://localhost:8080